# Blog info
blog_name: 方增鸿 Lred
slogan: 不管，我就要干拔<img class="ball-img" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f3c0.png">
url: http://www.lred.me

# Set avatar (Absolute url and relative url)
avatar: /images/headimg_dl.png

# Set favicon
favicon: /images/headimg_dl.png

# For seo
keywords: lred,redl,前端,前端开发,fzred,方增鸿,nodejs,JavaScript

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Project
    url: /project/
    target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/fzred
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: false # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 i@lred.me

# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: 支持一下
  tip: 扫一扫，支持forsigner
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png




post:
  header_align: LEFT # LEFT|CENTER
  showToc: true # true|false
  showComments: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style
personal_style: /css/personal-style.css

home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: POST  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 6b3c10d33962f5dff87fee3a9fa34391

# Comment service
# disqus_shortname: forsigner
duoshuo_shortname: lred


# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "1996."
    - "沉迷于编程，日渐消瘦."
    - "前端开发工程师，常用 HTML / CSS / JavaScript."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@fzred"
    text_value_url: https://github.com/fzred
  - type: mail
    icon: icon-mail
    text_key: Email
    text_value: "i@lred.me"
  - type: project
    icon: icon-github
    text_key: project
    text_value: "look"
    text_value_url: "/project"
  - type: location
    icon: icon-location
    text_value: 深圳

link:
  - name: Poem
    info: ${arg_wd}
    url: http://www.toyou.xyz/
    avatar: https://assets-cdn.github.com/images/icons/emoji/unicode/1f466.png

project:
  - type: personal
    name: gulp-local-css
    url: https://github.com/fzred/gulp-local-css
    intro: css局部作用域的gulp实现插件
  - type: personal
    name: excuse-me
    url: https://github.com/fzred/excuse-me
    intro: 斗图，没人是我的对手
  - type: personal
    name: battle-city
    url: https://github.com/fzred/Battle-City
    intro: 坦克大战